<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>bundleUUID</key>
    <string>ab72846e-6d4a-40c4-acd5-aa1e9426bedb</string>
    <key>name</key>
    <string>PythonTestOutput</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>test.error</string>
                </dict>
            </dict>
            <key>comment</key>
            <string>test error dot</string>
            <key>end</key>
            <string>[=-]+</string>
            <key>match</key>
            <string>(E)(?:[EFs\.]|$)</string>
        </dict>

        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>test.fail</string>
                </dict>
            </dict>
            <key>comment</key>
            <string>test fail dot</string>
            <key>end</key>
            <string>[=-]+</string>
            <key>match</key>
            <string>(F)(?:[EFs\.]|$)</string>
        </dict>


        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>test.skip</string>
                </dict>
            </dict>
            <key>comment</key>
            <string>test skip dot</string>
            <key>end</key>
            <string>[=-]+</string>
            <key>match</key>
            <string>(s)(?:[EFs\.]|$)</string>
        </dict>


        <dict>
            <key>begin</key>
            <string>\=+</string>
            <key>comment</key>
            <string>test error</string>
            <key>end</key>
            <string>\-+</string>
            <key>match</key>
            <string>ERROR: (.*)</string>
            <key>name</key>
            <string>test.error</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>\=+</string>
            <key>comment</key>
            <string>test fail</string>
            <key>end</key>
            <string>\-+</string>
            <key>match</key>
            <string>FAIL: (.*)</string>
            <key>name</key>
            <string>test.fail</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>File </string>
            <key>comment</key>
            <string>file in traceback</string>
            <key>end</key>
            <string>,</string>
            <key>match</key>
            <string>"(...*?)"</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>test.filename</string>
                </dict>
            </dict>

        </dict>
        <dict>
            <key>comment</key>
            <string>all test pass</string>
            <key>end</key>
            <string>\[Finished in [\d+\.]+s\]</string>
            <key>match</key>
            <string>OK</string>
            <key>name</key>
            <string>test.pass</string>
        </dict>
        <dict>
            <key>comment</key>
            <string>tests broken</string>
            <key>end</key>
            <string>\[Finished in (.*)]</string>
            <key>match</key>
            <string>FAILED (.*)</string>
            <key>name</key>
            <string>test.fail</string>
        </dict>
    </array>
    <key>scopeName</key>
    <string>tests.python</string>
    <key>uuid</key>
    <string>287bdb51-fb61-4680-805b-1cda356586cf</string>
</dict>
</plist>
